trigger:
  branches:
    include:
      - master

pool:
  name: 'payment-agent'

variables:
- group: 'docker' # Keep secrets secure in pipeline variables, 'docker' is the name of variable group in azure devops  
  

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and push Docker image
    steps:
    - script: echo $(docker-passwd) | docker login -u $(docker-username) --password-stdin # this reference from VG of names.
      displayName: 'Docker Login'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-hub'
        repository: 'avulakishore99/payment-repository'  # Use full path to repo
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: |
          latest
