
trigger:
  branches:
    include:
      - master

pool:
 name: 'payment-agent'

variables:
  DOCKER_PASSWORD: '16nf1a0101@.'
  DOCKER_USER: 'avulakishore99'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-hub'
        repository: 'payment'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
    - task: CmdLine@2
      inputs:
        script: |
          - script: echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
            displayName: 'Docker Login'
