
trigger:
  branches:
    include:
      - master

pool:
 name: 'payment-agent'


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-hub'
        repository: 'payment'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
