# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

variables:
 version: 3.5

steps:
 - task: DotNetCoreCLI@2
   displayName: 'resore-success'
   inputs:
     command: 'restore'
     majorVersion: '$(version)'
     projects: 'WebGoat.NET.sln'

 - task: UseDotNet@2
   inputs:
    packageType: 'sdk'
    version: '$(version)'

 - task: 'DotNetCoreCLI@2'
   inputs:
      command: 'build'
      projects: 'WebGoat.NET.sln'
      arguments: '--configuration$(buildconfiguration)'