trigger:
  branches:
    include:
      - master

pool:
  name: 'payment-agent-pool'
  demands: 
  - docker

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and push Docker image
    steps:
  
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-svc-connection' # ACR service connection NAME.
        repository: 'paymentACR1' # NAME OF ACR
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: |
          $(Build.BuildNumber)

- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - job: Build
  - deployment: 
    environment: 'Dev'
    dependsOn: Build
    displayName: Deploy to AKS
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'k8s-svc-connection'
              namespace: 'payment'
              manifests: 'manifest.yml'
              containers: |
                paymentACR1.azurecr.io/paymentacr1:$(Build.BuildNumber)
              arguments: --namespace=payment
