trigger:
  branches:
    include:
      - master

pool:
  name: 'payment-agent'

variables:
- group: 'docker' # Keep secrets secure in pipeline variables, 'docker' is the name of the variable group in azure devops  

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and push Docker image
    steps:
    - script: echo $(docker-passwd) | docker login -u $(docker-username) --password-stdin # Docker credentials from variable group
      displayName: 'Docker Login'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-hub'
        repository: 'avulakishore99/payment-repository'  # Use full path to repo
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: |
          $(Build.BuildNumber)

- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - deployment:
    environment: 'dev'
    displayName: Deploy to AKS
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'kubernetesServiceConnection'
              kubernetesServiceConnection: 'k8s-svc-connection'
              namespace: 'default'
              manifests: 'deployment.yml'
              containers: |
                avulakishore99/payment-repository:$(Build.BuildNumber)
              
