trigger:
- master

pool:
 name: 'payment-agent'

stages:
  - stage:
    jobs:
    - job: 
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acr-svc'
          repository: 'payment-repository'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'