trigger:
- master

pool:
 name: 'webgaot-pool'

stages:
  - stage:
    jobs:
    - job: 
      steps:
      - task: Docker@2
        displayName: 'docker build and pushed the image'
        inputs:
          containerRegistry: 'webgoat-dcr'
          repository: 'webgaotdotnet-IMAGE'
          command: 'build'
          Dockerfile: '**/dockerfile'
          addPipelineData: false
          addBaseImageData: false
          