apiVersion: apps/v1
kind: Deployment
metadata:
  name:  payment
  namespace: paymentnamespace
  labels:
    app:  payment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  payment
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
        - name: payment-container
          image: avulakishore99/payment-repository:$(Build.BuildId)  # Use BuildId with capital 'I'

        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - name:  payment
          containerPort:  80
          
